### ISSUE TITLE
Figure out how to handle .vue files

### ISSUE THREAD

**Issue by lmiller1990** [lmiller1990/vue-ts-jest#3]
Generally a vue file will always have a `export default...`. We also support additional named exports - for example.

```html
<script>
export default {}
export named const = 'named const'
</script>
```

Because we currently are using a simple shim for the vue files, eg:

```ts
declare module '*.vue' {
  const c: any
  export default c
}
```

`ts-jest` will notice this and error out with something like:

```js
 tests/index.spec.ts:4:10 - error TS2614: Module '"*.vue"' has no exported member 'named'. Did you mean to use 'import named from "*.vue"' instead?
```

Not sure how to handle this one.

**Comment by ahnpnl** [comment]
Does this mean any files with `.vue` extension should be handled by jest transformer ?

I am curious about the shim file, why do we need it ?

**Comment by lmiller1990** [comment]
Yes, all files with `.vue` need to be handled with the transformer.

The shim file is needed, otherwise VSCode/other editors don't know what to do with `.vue` files and will show an error in the editor.

I don't think this is something we can handle here, actually, but something the IDE will handle via some plugin.

**Comment by ahnpnl** [comment]
Ah I see. This case is IDE related. For Angular, they built Angular Language Service which is a ts plugin for IDE, see https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

Maybe someone in the community already did.

**Comment by lmiller1990** [comment]
Kind of, the `vetur` plugin does this.
